version: '3.7'

services:
  gunicorn:
    image: gabrieldolzan/tcc-gunicorn
    volumes:
      - static:/static
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    networks:
      - app-network
      - default
  db:
    image: postgres:15
    environment:
        TZ: "America/Sao_Paulo"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - default
  frontend:
    image: gabrieldolzan/tcc-vuejs
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network
  nginx:
    image: gabrieldolzan/tcc-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    tty: true
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - frontend
      - gunicorn
    networks:
      - app-network

volumes:
  static:
  postgres_data:

networks:
  app-network:
    driver: bridge
  default: